#pragma once

#include <bitbishop/engine/search.hpp>
#include <atomic>
#include <bitbishop/moves/position.hpp>
#include <mutex>
#include <optional>
#include <thread>
#include <vector>

namespace Uci {

/**
 * @brief Represents search limits for the UCI interface.
 *
 * This struct holds various parameters that control the search depth and timing.
 */
struct SearchLimits {
  std::optional<int> depth;         ///< Search depth limit (in ply)
  std::optional<int> movetime;      ///< Move time limit (in milliseconds)
  std::optional<int> wtime, btime;  ///< White/black time limits (in milliseconds)
  std::optional<int> winc, binc;    ///< White/black increment limits (in milliseconds)
  bool infinite = false;            ///< Flag for infinite search mode

  /**
   * @brief Parses arguments from a search uci command into a SearchLimits object.
   *
   * UCI command is like: `go depth 2` or `go movetime 5000`, etc...
   *
   * @return The built SearchLimits object.
   */
  static SearchLimits from_uci_cmd(const std::vector<std::string>& line);
};

/**
 * @brief Represents an event generated by a search worker.
 *
 * Search workers only publish data. Reporting/printing is done by the UCI control thread.
 */
enum class SearchReportKind : std::uint8_t {
  Iteration,
  Finish,
};

/**
 * @brief Structured search report event consumed by the UCI controller.
 */
struct SearchReport {
  SearchReportKind kind = SearchReportKind::Finish;
  Search::BestMove best;
  int depth = 0;
  Search::SearchStats stats{};
};

/**
 * @brief Manages the search process for UCI commands.
 *
 * This class handles the execution of search operations based on UCI parameters. It uses a background thread to
 * perform the search and publishes structured reports for the control thread to consume.
 */
class SearchWorker {
  std::thread worker;                  ///< Worker thread for search operations
  std::atomic<bool> stop_flag{false};  ///< Flag used to forward the stop order to the worker(s)
  std::atomic<bool> finished{true};    ///< Indicates whether worker thread has completed
  Board board;                         ///< Current chess board
  Position position;                   ///< Game position associated to the current chess board
  SearchLimits limits;                 ///< Current search parameters
  std::mutex reports_mutex;            ///< Synchronizes report queue access
  std::vector<SearchReport> reports;   ///< FIFO queue of generated search reports

  /**
   * @brief Executes the search algorithm in a background thread.
   */
  void run();

  /**
   * @brief Pushes one report event into the queue.
   */
  void push_report(SearchReport report);

 public:
  SearchWorker(Board board, SearchLimits limits);
  ~SearchWorker();

  /**
   * @brief Starts the search process with given parameters.
   *
   * Initializes the search controller with a new worker thread and parameters.
   * If no depth is specified, switches to infinite search mode.
   */
  void start();

  /**
   * @brief Requests the worker thread to stop naturaly the best move search.
   *
   * Thread finishes when a best move has been found.
   */
  void wait();

  /**
   * @brief Requests the worker thread to interrupt (stop early) the best move search.
   *
   * Thread interruption finishes early the best move search and may not be able to return a best move.
   * An intermediate state may be returned instead.
   */
  void request_stop();

  /**
   * @brief Returns whether the current worker run has finished.
   */
  [[nodiscard]] bool is_finished() const { return finished.load(); }

  /**
   * @brief Requests a stop then waits for completion.
   *
   * This is a blocking helper.
   */
  void stop();

  /**
   * @brief Moves all pending search reports out of the worker queue.
   *
   * This is thread-safe and intended to be called by the control thread.
   */
  [[nodiscard]] std::vector<SearchReport> drain_reports();
};

}  // namespace Uci
