#pragma once

#include <array>
#include <bitbishop/board.hpp>
#include <bitbishop/config.hpp>
#include <bitbishop/constants.hpp>
#include <bitbishop/piece.hpp>
#include <bitbishop/random.hpp>
#include <bitbishop/square.hpp>
#include <cstdint>

namespace Zobrist {

using Key = uint64_t;

/**
 * @brief Zobrist random key tables used for position hashing.
 *
 * Stores pre-generated random 64-bit keys for:
 * - each (piece, square) combination
 * - castling rights states
 * - en-passant file
 * - side to move
 *
 * These tables are XOR-combined to produce a unique hash for a board position.
 */
struct Tables {
  std::array<std::array<Key, Const::BOARD_SIZE>, Piece::DISTINCT_PIECES_COUNT> pieces{};
  std::array<Key, Const::CASTLING_RIGHTS_STATES_COUNT> castling{};
  std::array<Key, Const::EN_PASSANT_STATES_COUNT> en_passant{};
  Key side{};
};

/**
 * @brief Generates deterministic Zobrist random tables.
 *
 * Uses the splitmix64 generator with a fixed seed so that the same
 * random keys are produced across program runs and builds.
 *
 * @return Fully initialized Zobrist key tables.
 */
CX_FN Tables generate() {
  using namespace Random;
  using namespace Const;

  Tables zobrist_tbl{};
  uint64_t seed = 0x994c3ac5e71fafcbULL;  // NOLINT(readability-magic-numbers)

  for (int p_ind = 0; p_ind < Piece::DISTINCT_PIECES_COUNT; ++p_ind) {
    for (int sq = 0; sq < BOARD_SIZE; ++sq) {
      zobrist_tbl.pieces[p_ind][sq] = splitmix64(seed);
    }
  }

  for (int i = 0; i < CASTLING_RIGHTS_STATES_COUNT; ++i) {
    zobrist_tbl.castling[i] = splitmix64(seed);
  }

  for (int f = 0; f < EN_PASSANT_STATES_COUNT; ++f) {
    zobrist_tbl.en_passant[f] = splitmix64(seed);
  }

  zobrist_tbl.side = splitmix64(seed);

  return zobrist_tbl;
}

/**
 * @brief Global Zobrist tables instance.
 *
 * Generated once (typically at compile time) and reused for all hash
 * computations during program execution.
 */
CX_INLINE Tables tables = generate();

/**
 * @brief Converts a Piece to its Zobrist table index.
 *
 * Piece indices are arranged as:
 * - White pieces: 0–5
 * - Black pieces: 6–11
 *
 * Ordering within each color:
 * Pawn, Knight, Bishop, Rook, Queen, King.
 *
 * @param piece Piece to convert.
 * @return Index into Tables::pieces.
 */
CX_FN int piece_index(Piece piece) {
  // NOLINTBEGIN(readability-magic-numbers)
  int base = (piece.color() == Color::WHITE) ? 0 : 6;

  switch (piece.type()) {
    case Piece::Type::PAWN:
      return base + 0;
    case Piece::Type::KNIGHT:
      return base + 1;
    case Piece::Type::BISHOP:
      return base + 2;
    case Piece::Type::ROOK:
      return base + 3;
    case Piece::Type::QUEEN:
      return base + 4;
    case Piece::Type::KING:
      return base + 5;
  }
  // NOLINTEND(readability-magic-numbers)

  return 0;
}

/**
 * @brief Computes the Zobrist hash of a board position.
 *
 * Zobrist hashing represents a chess position as a 64-bit key generated by
 * XOR-combining random numbers associated with individual elements of the
 * position. Each feature of the board contributes a deterministic random value
 * from the pre-generated Zobrist tables.
 *
 * The resulting key uniquely (with very high probability) identifies the
 * position and is typically used for transposition tables, repetition
 * detection, and caching search results.
 *
 * The hash is constructed from the following components:
 *
 * 1. Piece placement
 *    Each (piece type, square) pair has an associated random key. For every
 *    piece present on the board, the corresponding key is XORed into the hash.
 *
 * 2. Side to move
 *    If the side to move is black, a dedicated random key is XORed into the
 *    hash. This ensures identical board positions with different players to
 *    move produce different hashes.
 *
 * 3. Castling rights
 *    Castling rights are encoded as a 4-bit value representing the availability
 *    of the following rights:
 *      - White kingside
 *      - White queenside
 *      - Black kingside
 *      - Black queenside
 *
 *    The resulting value (0–15) indexes a table of random keys. The selected
 *    key is XORed into the hash.
 *
 * 4. En-passant file
 *    If an en-passant square exists, the file of that square (a–h) is used to
 *    select one of eight random keys. That key is XORed into the hash.
 *
 * XOR is used because it has two important properties:
 *  - Reversibility: applying the same key twice cancels it out
 *  - Order independence: the result is independent of the order of operations
 *
 * These properties allow efficient incremental hash updates when making or
 * unmaking moves.
 *
 * @param board Board position to hash.
 * @return 64-bit Zobrist hash key representing the position.
 */
Zobrist::Key compute_hash(const Board& board);

}  // namespace Zobrist
