name: Reusable macOS Build Test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      arch:
        required: true
        type: string
      configure_preset:
        required: true
        type: string
      build_preset:
        required: true
        type: string
      test_preset:
        required: true
        type: string

permissions:
  contents: read

jobs:
  macos-build:
    runs-on: ${{ inputs.runner }}
    name: macOS Build & Test

    steps:
      - uses: actions/checkout@v4

      - name: Setup pre-installed VCPKG
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Cache VCPKG
        run: |
          # Use the GitHub Actions cache as a binary source.
          echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV
        env:
          ACTIONS_CACHE_URL: ${{ secrets.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.ACTIONS_RUNTIME_TOKEN }}

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ inputs.arch }}-cmake-${{ inputs.build_preset }}-${{ hashFiles('CMakeLists.txt', '**/*.cmake') }}
          restore-keys: ${{ runner.os }}-${{ inputs.arch }}-cmake-

      - name: Configure (${{ inputs.configure_preset }})
        uses: ./.github/actions/_log_to_gh_summary_bash
        with:
          step-name: Configure (${{ inputs.configure_preset }})
          command: "cmake --preset ${{ inputs.configure_preset }}"

      - name: Build (${{ inputs.build_preset }})
        uses: ./.github/actions/_log_to_gh_summary_bash
        with:
          step-name: Build (${{ inputs.build_preset }})
          command: "cmake --build --preset ${{ inputs.build_preset }}"

      - name: Test (${{ inputs.test_preset }})
        uses: ./.github/actions/_log_to_gh_summary_bash
        with:
          step-name: Test (${{ inputs.test_preset }})
          command: "ctest --preset ${{ inputs.test_preset }} --output-on-failure"
