name: Reusable Windows Build Test

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      arch:
        required: true
        type: string
      name:
        required: true
        type: string
      configure_preset:
        required: true
        type: string
      build_preset:
        required: true
        type: string
      test_preset:
        required: true
        type: string

permissions:
  contents: read

jobs:
  windows-build:
    runs-on: ${{ inputs.runner }}
    name: Windows Build & Test

    steps:
      - uses: actions/checkout@v4

      - name: Cache VCPKG
        uses: actions/cache@v4
        with:
          path: |
            C:\vcpkg\installed
            C:\vcpkg\packages
            C:\vcpkg\buildtrees
            ~\AppData\Local\vcpkg\archives
          key: ${{ runner.os }}-${{ inputs.arch }}-vcpkg-${{ inputs.name }}-${{ hashFiles('vcpkg.json') }}
          restore-keys: ${{ runner.os }}-${{ inputs.arch }}-vcpkg-

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ inputs.arch }}-cmake-${{ inputs.name }}-${{ hashFiles('CMakeLists.txt', '**/*.cmake') }}
          restore-keys: ${{ runner.os }}-${{ inputs.arch }}-cmake-

      - name: Configure (${{ inputs.configure_preset }})
        uses: ./.github/actions/_log_to_gh_summary_pwsh
        env:
          VCPKG_ROOT: C:\vcpkg
        with:
          step-name: Configure (${{ inputs.configure_preset }})
          command: "cmake --preset ${{ inputs.configure_preset }}"

      - name: Build (${{ inputs.build_preset }})
        uses: ./.github/actions/_log_to_gh_summary_pwsh
        with:
          step-name: Build (${{ inputs.build_preset }})
          command: "cmake --build --preset ${{ inputs.build_preset }}"

      - name: Test (${{ inputs.test_preset }})
        uses: ./.github/actions/_log_to_gh_summary_pwsh
        with:
          step-name: Test (${{ inputs.test_preset }})
          command: "ctest --preset ${{ inputs.test_preset }} --output-on-failure"
