name: Clang Tidy Linting

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  clang-tidy-linting:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} - ${{ matrix.build_preset }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04-arm
            arch: arm64
            configure_preset: clang_debug
            build_preset: clang_debug

    steps:
      - uses: actions/checkout@v6

      - name: Setup, configure, and run clang-tidy
        uses: ./.github/actions/_setup_configure_build_linux
        with:
          arch: ${{ matrix.arch }}
          configure-preset: ${{ matrix.configure_preset }}
          build-preset: ${{ matrix.build_preset }}
          build-target: clang-tidy
          build-step-name: Run clang-tidy
