name: MacOS Build Test

on:
  pull_request:
    branches: [ main ]
    types: [labeled, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  macos-intel-build:
    if: |
      github.event_name == 'pull_request' &&
      (
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'run-pre-merge-checks'
        ) ||
        (
          github.event.action != 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'run-pre-merge-checks')
        )
      )
    name: macos-26-intel - quick-validation-clang-release
    uses: ./.github/workflows/_rwf_macos_build_test.yaml
    with:
      runner: macos-26-intel
      arch: intel
      configure_preset: clang_release
      build_preset: clang_release
      test_preset: quick-validation-clang-release
    secrets: inherit

  macos-arm-build:
    if: |
      github.event_name == 'pull_request' &&
      (
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'run-pre-merge-checks'
        ) ||
        (
          github.event.action != 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'run-pre-merge-checks')
        )
      )
    name: macos-26 - quick-validation-clang-release
    uses: ./.github/workflows/_rwf_macos_build_test.yaml
    with:
      runner: macos-26
      arch: arm64
      configure_preset: clang_release
      build_preset: clang_release
      test_preset: quick-validation-clang-release
    secrets: inherit
