name: MacOS Build Test

on:
  workflow_dispatch:
  push:
  # pull_request:
  #   types: [labeled, synchronize]

concurrency:
  group: pr-${{ github.event.pull_request.number }}-macos-build
  cancel-in-progress: true

jobs:
  macos-build:
    # if: contains(github.event.pull_request.labels.*.name, 'run-pre-merge-checks')
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.runner }} - ${{ matrix.test_preset }}

    strategy:
      matrix:
        include:
          - runner: macos-26-intel
            arch: intel
            name: clang_debug
            configure_preset: clang_debug
            build_preset: clang_debug
            test_preset: quick-validation-clang-debug

          - runner: macos-26
            arch: arm64
            name: clang_debug
            configure_preset: clang_debug
            build_preset: clang_debug
            test_preset: quick-validation-clang-debug

          - runner: macos-26-intel
            arch: intel
            name: clang_release
            configure_preset: clang_release
            build_preset: clang_release
            test_preset: quick-validation-clang_release

          - runner: macos-26
            arch: arm64
            name: clang_release
            configure_preset: clang_release
            build_preset: clang_release
            test_preset: quick-validation-clang_release

    steps:
      - uses: actions/checkout@v4

      - name: Setup pre-installed VCPKG
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Cache VCPKG
        run: |
          # Use the GitHub Actions cache as a binary source
          echo "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" >> $GITHUB_ENV
        env:
          # These variables are required for the 'x-gha' provider to talk to GitHub's cache API
          ACTIONS_CACHE_URL: ${{ secrets.ACTIONS_CACHE_URL }}
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.ACTIONS_RUNTIME_TOKEN }}

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ matrix.arch }}-cmake-${{ matrix.name }}-${{ hashFiles('CMakeLists.txt', '**/*.cmake') }}
          restore-keys: ${{ runner.os }}-${{ matrix.arch }}-cmake-

      - name: Configure (${{ matrix.configure_preset }})
        uses: ./.github/actions/_log_to_gh_summary
        with:
          step-name: Configure (${{ matrix.configure_preset }})
          command: "cmake --preset ${{ matrix.configure_preset }}"

      - name: Build (${{ matrix.build_preset }})
        uses: ./.github/actions/_log_to_gh_summary
        with:
          step-name: Build (${{ matrix.build_preset }})
          command: "cmake --build --preset ${{ matrix.build_preset }}"

      - name: Test (${{ matrix.test_preset }})
        uses: ./.github/actions/_log_to_gh_summary
        with:
          step-name: Test (${{ matrix.test_preset }})
          command: "ctest --preset ${{ matrix.test_preset }} --output-on-failure"
