name: Windows Build Test

on:
  pull_request:
    branches: [ main ]
    types: [labeled, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows-2022-build:
    if: |
      github.event_name == 'pull_request' &&
      (
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'run-pre-merge-checks'
        ) ||
        (
          github.event.action != 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'run-pre-merge-checks')
        )
      )
    name: windows-2022 - quick-validation-msvc-release
    uses: ./.github/workflows/_rwf_windows_build_test.yaml
    with:
      runner: windows-2022
      arch: x64
      configure_preset: msvc_release
      build_preset: msvc_release
      test_preset: quick-validation-msvc-release
    secrets: inherit

  windows-2025-build:
    if: |
      github.event_name == 'pull_request' &&
      (
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'run-pre-merge-checks'
        ) ||
        (
          github.event.action != 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'run-pre-merge-checks')
        )
      )
    name: windows-2025 - quick-validation-msvc-release
    uses: ./.github/workflows/_rwf_windows_build_test.yaml
    with:
      runner: windows-2025
      arch: x64
      configure_preset: msvc_release
      build_preset: msvc_release
      test_preset: quick-validation-msvc-release
    secrets: inherit

  windows-11-arm-build:
    if: |
      github.event_name == 'pull_request' &&
      (
        (
          github.event.action == 'labeled' &&
          github.event.label.name == 'run-pre-merge-checks'
        ) ||
        (
          github.event.action != 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'run-pre-merge-checks')
        )
      )
    name: windows-11-arm - quick-validation-msvc-release
    uses: ./.github/workflows/_rwf_windows_build_test.yaml
    with:
      runner: windows-11-arm
      arch: arm64
      configure_preset: msvc_release
      build_preset: msvc_release
      test_preset: quick-validation-msvc-release
    secrets: inherit
